spring:
    main:
        allow-circular-references: true
    application: 
        name: Bill
    datasource: 
        url: jdbc:postgresql://localhost:15001/Bill
        username: tk-apap-50
        password: tk-apap-50
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
server:
    port: 8085
Bill:
    app:
        jwtSecret: "hPjbJwZKskRmCnzroyAZfglqSKexYmxKeYPvSvJ"
        jwtExpirationMs: 86400000